// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: enrollment_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createEnrollmentApplication = `-- name: CreateEnrollmentApplication :execresult
INSERT INTO enrollment_application (student, project, schedule) VALUES (?, ?, ?)
`

type CreateEnrollmentApplicationParams struct {
	Student  int32
	Project  int32
	Schedule int32
}

func (q *Queries) CreateEnrollmentApplication(ctx context.Context, arg CreateEnrollmentApplicationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEnrollmentApplication, arg.Student, arg.Project, arg.Schedule)
}
