// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type Company struct {
	ID       int32
	Name     string
	Ruc      string
	ImageUrl sql.NullString
}

type EnrollmentApplication struct {
	ID        int32
	Student   int32
	Project   int32
	Schedule  int32
	AppliedOn sql.NullTime
	Status    string
}

type EnrollmentGenerated struct {
	ID                    int32
	EnrollmentApplication int32
	ApprovedBy            int32
	GeneratedAt           time.Time
}

type Project struct {
	ID          int32
	Company     int32
	Name        string
	Description string
	Starts      time.Time
	Ends        time.Time
}

type ProjectSchedule struct {
	ID       int32
	Project  int32
	Schedule string
}

type Schedule struct {
	Code       string
	Desciption string
}

type User struct {
	ID           int32
	IDCardNumber string
	Name         string
	Surname      string
	Email        string
	Password     string
	Role         string
	DateOfBirth  sql.NullTime
	IsAGraduate  sql.NullBool
	Level        sql.NullInt32
}

type UserRole struct {
	Code        string
	Description string
}
