version: '3'

services:
  enrollment-app:
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1