version: '3'

services:
  enrollment-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_HOST: 'mysql'
      DB_NAME: 'ppugenrollment'
    ports:
      - '8080:80'
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: unless-stopped
    command: --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_DATABASE: 'ppugenrollment'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3333:3306'
    expose:
      - '3333'
    volumes:
      - ./db-data/mysql/:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d